### ISSUE TITLE
Implement YouTube search

### ISSUE THREAD

**Issue by duha54rus** [duha54rus/Discord-Music-Bot#7]

**Comment by piunov1998** [comment]
Working on this on, check my new brach

**Comment by duha54rus** [comment]
So it just spawns URLs into the chat.
But what if there was a way to just click the appropriate video’s title to download it? We could remove URLs from the print AND increase UX!
You should try and do that, @piunov1998.

**Comment by piunov1998** [comment]
And how do u see it? 
1. I just started
2. I cant make clickable elements for bot.
3. Im going to add some subcommand which will execute download function with chosen video url as argument

**Comment by piunov1998** [comment]
Check new update
